<?php
/** @var \APP\Entity\Theme $theme */
$theme = $this->theme;
/** @var \APP\Entity\Examen[] $examens */
$examens = $this->examens;
/** @var \APP\Entity\Cours[] $cours */
$cours = $this->cours;
?>

<ol class="breadcrumb">
    <li><a href="/">Accueil</a></li>
    <li><a href="/theme/lister">Gestion du contenu</a></li>
    <li class="active"><?php echo $theme->getNom(); ?></li>
</ol>

<div class="page-header">
    <h2>
        <?php echo $theme->getNom(); ?>
        <!-- Publication -->
        <?php if ($theme->isPublished()) { ?>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                  data-toggle="tooltip" data-placement="right" title="Publié"></span>
        <?php } else { ?>
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                  data-toggle="tooltip" data-placement="right" title="Cliquer pour publier"
                  data-theme="<?php echo $theme->getIdTheme(); ?>"></span>
        <?php } ?>
    </h2>
</div>
<h3>Examens</h3>

<div class="col-sm-4">
    <table class="table table-striped table-hover table-link">
        <col width="94%">
        <col width="1%">

        <tbody>
        <?php foreach ($examens as $examen) { ?>
            <tr class="tr_examen" data-id="<?php echo $examen->getIdExamen(); ?>">
                <td class="examen_link">
                    <span class="nom_examen"><?php echo $examen->getNom(); ?></span>

                    <!-- Publication -->
                <span class="is_published" style="float: right;">
                <?php if ($examen->isPublished()) { ?>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Publié"></span>
                <?php } else { ?>
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Non publié"></span>
                <?php } ?>
                </span>
                </td>
                <td>
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <?php if (!$examen->isPublished()) { ?>
                                <li><a href="#" data-toggle="modal" class="publish_link" data-target="#publishExamenModal"
                                       data-id="<?php echo $examen->getIdExamen(); ?>">Publier</a></li>
                            <?php } ?>
                            <li><a href="#" data-toggle="modal" data-target="#deleteExamenModal"
                                   data-id="<?php echo $examen->getIdExamen(); ?>">Supprimer</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>

    <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#addExamenModal">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Créer un nouvel examen
    </a>
</div>

<div class="clearfix"></div>

<h3>Cours</h3>
<div class="col-sm-4">
    <table class="table table-striped table-hover table-link">
        <col width="94%">
        <col width="1%">

        <tbody>
        <?php foreach ($cours as $c) { ?>
            <tr class="tr_cours" data-id="<?php echo $c->getIdCours(); ?>">
                    <td class="cours_link">
                        <?php echo $c->getNom(); ?>
                    </td>

                <td>
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li><a href="#" data-toggle="modal" data-target="#deleteCoursModal"
                                   data-id="<?php echo $c->getIdCours(); ?>">Supprimer</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>

    <a class="btn btn-primary" href="/cours/creer?id_theme=<?php echo $theme->getIdTheme(); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Ajouter un nouveau cours
    </a>
</div>

<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="publishExamenModal" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmation de publication</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
                    La publication de cet examen entrainera sa diffusion sur les applications mobiles.
                </div>
                Voulez-vous vraiment publier l'examen : <span class="nom_examen"></span> ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary examen_publish" data-id="">Confirmer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-sm" id="deleteExamenModal" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmation de suppression</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
                    La suppression de cet examen entrainera la suppression des questions associées
                </div>
                Voulez-vous vraiment supprimer l'examen : <span class="nom_examen"></span> ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary examen_delete" data-id="">Confirmer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-sm" id="deleteCoursModal" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmation de suppression</h4>
            </div>
            <div class="modal-body">
                Voulez-vous vraiment supprimer ce cours ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary cours_delete" data-id="">Confirmer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addExamenModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Ajout d'un examen</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form method="post"  class="form-horizontal"  action="/examen/saveExamen" role="form" data-toggle="validator">
                        <input type="hidden" name="id_theme" id="id_theme" value="<?php echo $theme->getIdTheme(); ?>"/>
                        <!-- Nom -->
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="nom">Nom : </label>

                            <div class="col-sm-6">
                                <input class="form-control" name="nom" id="nom"
                                       placeholder="Nom de l'examen" type="text" maxlength="30" required/>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary add_examen">Sauvegarder</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>