<h2>Création d'un thème</h2>

<form method="post"  class="form-horizontal"  action="/theme/saveTheme" role="form" data-toggle="validator">
    <!-- Nom -->
    <div class="form-group">
        <label class="col-sm-1 control-label" for="nom">Nom : </label>

        <div class="col-sm-3">
            <input class="form-control" name="nom" id="nom"
                   placeholder="Nom du thème" type="text" maxlength="30" required/>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <button type="submit" class="btn btn-default">Valider</button>
</form>