<?php
/** @var \APP\Entity\Examen[] $examens_blancs */
$examens_blancs = $this->examens_blancs;
?>

<ol class="breadcrumb">
    <li><a href="/">Accueil</a></li>
    <li><a href="/theme/lister">Gestion du contenu</a></li>
    <li class="active">Examens blancs</li>
</ol>

<h2>Liste des examens blancs</h2>
<div class="col-sm-4">
    <table class="table table-striped table-hover table-link">
        <col width="94%">
        <col width="1%">

        <tbody>
<?php foreach ($examens_blancs as $examen) { ?>
    <tr class="tr_examen" data-id="<?php echo $examen->getIdExamen(); ?>">
        <td class="examen_link">
            <?php echo $examen->getNom(); ?>

            <!-- Publication -->
                <span class="is_published" style="float: right;">
                <?php if ($examen->isPublished()) { ?>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Publié"></span>
                <?php } else { ?>
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Non publié"></span>
                <?php } ?>
                </span>
        </td>
        <td>
            <div class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="true">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                    <?php if (!$examen->isPublished()) { ?>
                        <li><a href="#" data-toggle="modal" data-target="#publishExamenModal"
                               data-id="<?php echo $examen->getIdExamen(); ?>">Publier</a></li>
                    <?php } ?>
                    <li><a href="#" data-toggle="modal" data-target="#deleteExamenModal"
                           data-id="<?php echo $examen->getIdExamen(); ?>">Supprimer</a></li>
                </ul>
        </td>
    </tr>
<?php } ?>
        </tbody>
    </table>
    <a class="btn btn-primary"  href="#" data-toggle="modal" data-target="#addExamenModal">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Créer un nouvel examen
    </a>
</div>

<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="publishExamenModal" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmation de publication</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">
                    <strong>Attention : </strong>La publication de cet examen entrainera sa diffusion sur les applications mobiles.
                </div>
                Voulez-vous vraiment publier l'examen : <span class="nom_examen"></span> ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary examen_publish" data-id="">Confirmer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-sm" id="deleteExamenModal" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmation de suppression</h4>
            </div>
            <div class="modal-body">
                Voulez-vous vraiment supprimer cet examen ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary examen_delete" data-id="">Confirmer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addExamenModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Ajout d'un examen</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form method="post"  class="form-horizontal"  action="/examen/saveExamen" role="form" data-toggle="validator">
                        <!-- Nom -->
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="nom">Nom : </label>

                            <div class="col-sm-6">
                                <input class="form-control" name="nom" id="nom"
                                       placeholder="Nom de l'examen" type="text" maxlength="30" required/>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary add_examen">Sauvegarder</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>