<?php
/** @var \APP\Entity\Examen[] $examens_blancs */
$examens_blancs = $this->examens_blancs;
?>

<h2>Liste des examens blancs</h2>
<div class="list-group" style="width: 200px">
    <?php foreach ($examens_blancs as $examen) { ?>
        <a href="/examen/afficher?id=<?php echo $examen->getIdExamen(); ?>" class="list-group-item">
            <?php echo $examen->getNom(); ?>

            <!-- Publication -->
            <span style="float: right;">
                <?php if ($examen->isPublished()) { ?>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Publié"></span>
                <?php } else { ?>
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Non publié"></span>
                <?php } ?>
            </span>
        </a>
    <?php } ?>
</div>

<a class="btn btn-primary" href="/examen/creer?id_theme=0">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Créer un nouvel examen
</a>

<script type="application/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>