<?php
/** @var \APP\Entity\Examen[] $examens_blancs */
$examens_blancs = $this->examens_blancs;
?>

<h2>Liste des examens blancs</h2>
<?php foreach ($examens_blancs as $examen) { ?>
    <div class="div_examen" data-id="<?php echo $examen->getIdExamen(); ?>">
        <div class="btn-group btn-group-lg" role="group" aria-label="...">
            <button type="button" class="btn btn-default examen_link" style="width: 200px"
                    onclick="window.location.href = '/examen/afficher?id=<?php echo $examen->getIdExamen(); ?>'">
                <?php echo $examen->getNom(); ?>

                <!-- Publication -->
                <span class="is_published" style="float: right;">
                <?php if ($examen->isPublished()) { ?>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Publié"></span>
                <?php } else { ?>
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Non publié"></span>
                <?php } ?>
                </span>
            </button>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                    aria-expanded="false">
                <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <?php if (!$examen->isPublished()) { ?>
                    <li><a href="#" class="examen_publication">Publier</a></li>
                <?php } ?>
                <li><a href="#" class="examen_delete">Supprimer</a></li>
            </ul>
        </div>
    </div>
<?php } ?>

<br/>

<a class="btn btn-primary" href="/examen/creer?id_theme=0">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Créer un nouvel examen
</a>