<?php
/** @var \APP\Entity\Theme[] $themes */
$themes = $this->themes;
?>

<ol class="breadcrumb">
    <li><a href="/">Accueil</a></li>
    <li class="active">Gestion du contenu</li>
</ol>

<h2>Liste des thèmes</h2>

<div class="col-sm-4">
    <table class="table table-striped table-hover table-link">
        <col width="94%">
        <col width="1%">

        <tbody>
        <tr>
            <td class="btn-info examens_blancs_link" colspan="2">
                Examens blancs
            </td>
        </tr>
        <?php foreach ($themes as $theme) { ?>
            <tr class="tr_theme" data-id="<?php echo $theme->getIdTheme(); ?>">
                <td class="theme_link" aria-label="...">
                    <span class="nom_theme"><?php echo $theme->getNom(); ?></span>
                    <!-- Publication -->
            <span class="is_published" style="float: right;">
                <?php if ($theme->isPublished()) { ?>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Publié"></span>
                <?php } else { ?>
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Non publié"></span>
                <?php } ?>
            </span>
                </td>

                <td>
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <?php if (!$theme->isPublished()) { ?>
                                <li><a href="#" class="theme_publication">Publier</a></li>
                            <?php } ?>
                            <li><a href="#" data-toggle="modal" data-target="#deleteModal"
                                   data-id="<?php echo $theme->getIdTheme(); ?>">Supprimer</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#addThemeModal">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Créer un thème
    </a>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmation de suppression</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">
                    <strong>Attention : </strong>La suppression de ce thème entrainera la suppression des données associées (Examens, Questions et Cours)
                </div>
                Voulez-vous vraiment supprimer le thème : <span class="nom_theme"></span> ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary theme_delete" data-id="">Confirmer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addThemeModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Ajout d'un thème</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form method="post" class="form-horizontal" action="/theme/saveTheme" role="form"
                          data-toggle="validator">
                        <!-- Nom -->
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="nom_theme">Nom : </label>

                            <div class="col-sm-6">
                                <input class="form-control" name="nom" id="nom_theme"
                                       placeholder="Nom du thème" type="text" maxlength="30" required/>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary add_theme">Sauvegarder</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>