<?php
/** @var \APP\Entity\Theme[] $themes */
$themes = $this->themes;
?>
<h2>Liste des thèmes</h2>

<div class="list-group" style="width: 200px">
    <a href="/theme/listerExamensBlanc" class="list-group-item list-group-item-info">Examens blancs</a>
    <?php foreach ($themes as $theme) { ?>
        <a href="/theme/afficher?id=<?php echo $theme->getIdTheme(); ?>" class="list-group-item">
            <?php echo $theme->getNom(); ?>

            <!-- Publication -->
            <span style="float: right;">
                <?php if ($theme->isPublished()) { ?>
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Publié"></span>
                <?php } else { ?>
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"
                          data-toggle="tooltip" data-placement="right" title="Non publié"></span>
                <?php } ?>
            </span>
        </a>
    <?php } ?>
</div>

<a class="btn btn-primary" href="/theme/creer">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Créer un thème
</a>

<script type="application/javascript">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>