<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Load CSS -->
    <link href="/css/default.css"	type="text/css" rel="stylesheet" />
    <?php foreach ($this->css as $css){ ?>
        <link href="/module/css/<?php echo $css ?>.css"	type="text/css" rel="stylesheet" />
    <?php } ?>
    <!-- Bootstrap -->
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/lib/jquery-2.1.4.min.js"></script>
    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="/lib/validator.js"></script>
    <!-- Load JS Scripts -->
    <?php foreach ($this->js as $js){ ?>
        <script src="/module/js/<?php echo $js ?>.js" type="text/javascript"></script>
    <?php } ?>
    <title>Cap Horn - Permis Bateau</title>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Permis Bateau</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Accueil</a></li>
                    <li><a href="/theme/lister">Gestion du contenu</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="starter-template">
        <?php
        /** @var \FSF\View $this */
        echo $this->currentView->render();
        ?>
        </div>
    </div>
</body>
</html>