<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <!-- Bootstrap -->
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="/lib/jquery-2.1.4.min.js"></script>
</head>
<body>
    <h1>
        <a href="/">Permis Bateau</a>
    </h1>

    <div>
        <?php
        /** @var \FSF\View $this */
        echo $this->currentView->render();
        ?>
    </div>
    <h1>

    </h1>
</body>
</html>