<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <!-- Bootstrap -->
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="/lib/jquery-2.1.4.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Permis Bateau</a>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="starter-template">
        <?php
        /** @var \FSF\View $this */
        echo $this->currentView->render();
        ?>
        </div>
    </div>
</body>
</html>