<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template text-center">
                <div class="page-header">
                <h2>404 Not Found</h2>
                </div>
                <div class="text-warning">
                    Désolé cette page n'existe pas
                </div>
                <div class="help-block">
                    <a href="/" class="btn btn-primary">
                        <span class="glyphicon glyphicon-home"></span>
                        Retour à l'accueil
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
