<div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Connexion</div>
        </div>

        <div style="padding-top:30px" class="panel-body">
            <div style="display:none" class="alert alert-danger alert-dismissible col-sm-12">
                <button type="button" class="close"><span aria-hidden="true">&times;</span></button>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span id="login-alert"></span>
            </div>

            <form id="loginform" class="" role="form" method="post" data-toggle="validator">
                <div class="form-group">
                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="username" value=""
                               placeholder="Nom d'utilisateur" required>
                    </div>
                </div>
                <div class="form-group">
                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password"
                               placeholder="Mot de passe" required>
                    </div>
                </div>
                <div style="margin-top:10px" class="form-group">
                    <div class="col-sm-12 controls">
                        <a id="btn-login" href="#" class="btn btn-success">Se connecter</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>