<?php
/** @var \APP\Entity\Examen $examen */
$examen = $this->examen;
/** @var \APP\Entity\Question[] $questions */
$questions = $this->questions;
?>
<h2><?php echo $examen->getNom(); ?></h2>

<table class="table table-striped table-hover" style="width: 80%">
    <col width="5%">
    <col width="95%">

    <thead>
    <tr>
        <th>Numéro</th>
        <th>Enoncé</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->questions as $question) {
        /** @var \APP\Entity\Question $question */ ?>
        <tr onclick="window.location='/question/afficher?id=<?php echo $question->getId(); ?>'" style="cursor: pointer">
            <td><?php echo $question->getNumeroQuestion(); ?></td>
            <td><?php echo $question->getEnonceQuestion(); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<a href="/question/creer?id_examen=<?php echo $examen->getIdExamen(); ?>">Créer une nouvelle question</a>