<h2>Création d'un examen</h2>

<form method="post"  class="form-horizontal"  action="/examen/saveExamen">
    <input type="hidden" name="id_theme" id="id_theme" value="<?php echo $this->id_theme; ?>"/>
    <!-- Numéro -->
    <div class="form-group">
        <label class="col-sm-1 control-label" for="numero_examen">Numéro : </label>

        <div class="col-sm-4">
            <input class="form-control" name="numero_examen" id="numero_examen"
                   placeholder="Numéro de l'examen" type="number"/>
        </div>
    </div>
    <!-- Nom -->
    <div class="form-group">
        <label class="col-sm-1 control-label" for="nom">Nom : </label>

        <div class="col-sm-4">
            <input class="form-control" name="nom" id="nom"
                   placeholder="Nom de l'examen" type="text"/>
        </div>
    </div>
    <button type="submit" class="btn btn-default">Valider</button>
</form>