<?php
/** @var \APP\Entity\Question $question */
$question = $this->question;
if($question->getId() == 0){ ?>
<h2>Création d'une question</h2>
<?php }else{ ?>
    <h2>Modification d'une question</h2>
<?php } ?>

<form method="post" id="form_question_creation" class="form-horizontal" action="/question/saveQuestion"
      enctype="multipart/form-data">
    <input type="hidden" name="id_examen" id="id_examen" value="<?php echo $this->id_examen; ?>"/>
    <input type="hidden" name="id_question" id="id_question" value="<?php echo $question->getId(); ?>"/>
    <!-- Enonce -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="question_enonce">Enoncé de la question : </label>

        <div class="col-sm-5">
            <textarea class="form-control" name="question_enonce" id="question_enonce"
                      placeholder="Enoncé de la question"
                      maxlength="150" rows="3" required><?php echo $question->getEnonceQuestion() ?></textarea>

            <div class="help-block with-errors"></div>
        </div>
    </div>
    <!-- Réponse A -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_A">Réponse A : </label>

        <div class="input-group col-sm-5">
            <span class="input-group-addon">
                <input name="is_correct_A" id="is_correct_A" type="checkbox" data-checkbox="true"
                       <?php if($question->isCorrectA()) echo "checked"; ?>/>
            </span>
            <input class="form-control" name="enonce_A" id="enonce_A" placeholder="Réponse A" maxlength="50"
                value="<?php echo $question->getEnonceA()?>"/>
        </div>
    </div>
    <!-- Réponse B -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_B">Réponse B : </label>

        <div class="input-group col-sm-5">
            <span class="input-group-addon">
                <input name="is_correct_B" id="is_correct_B" type="checkbox" data-checkbox="true"
                    <?php if($question->isCorrectB()) echo "checked"; ?>/>
            </span>
            <input class="form-control" name="enonce_B" id="enonce_B" placeholder="Réponse B" maxlength="50"
                   value="<?php echo $question->getEnonceB()?>"/>
        </div>
    </div>
    <!-- Réponse C -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_C">Réponse C : </label>

        <div class="input-group col-sm-5">
            <span class="input-group-addon">
                <input name="is_correct_C" id="is_correct_C" type="checkbox" data-checkbox="true"
                    <?php if($question->isCorrectC()) echo "checked"; ?>/>
            </span>
            <input class="form-control" name="enonce_C" id="enonce_C" placeholder="Réponse C" maxlength="50"
                   value="<?php echo $question->getEnonceC()?>"/>
        </div>
    </div>
    <!-- Réponse D -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_D">Réponse D : </label>

        <div class="input-group col-sm-5">
            <span class="input-group-addon">
                <input name="is_correct_D" id="is_correct_D" type="checkbox" data-checkbox="true"
                    <?php if($question->isCorrectD()) echo "checked"; ?>/>
            </span>
            <input class="form-control" name="enonce_D" id="enonce_D" placeholder="Réponse D" maxlength="50"
                   value="<?php echo $question->getEnonceD()?>"/>
        </div>
    </div>
    <!-- Image -->
    <div class="form-group">
        <label class="col-sm-2 control-label">Image : </label>

        <div class="input-group col-sm-5">
            <div style="margin: 5px;" id="div_image">
                <?php
                $modelImage = new \APP\Model\Image();
                $image = $modelImage->get($question->getIdImage());
                if (!is_null($image) && $image->imageFileExist()) {
                    $image_url = "/public/datas/images/".\APP\Module\Image\Generator::SD.'/'.$image->getNomImagePNG();
                    echo '<img src="'.$image_url.'"/>';
                } ?>
            </div>
            <input class="form-control" name="image" id="image" type="file"/>
        </div>
    </div>
    <div class="has-error">
        <div class="col-sm-5 help-block with-errors" id="error_checkbox" style="display: none;">
            <ul class="list-unstyled">
                <li>Veuillez sélectionner au moins une réponse correcte</li>
            </ul>
        </div>
        <div class="col-sm-5 help-block with-errors" id="error_nb_responses" style="display: none;">
            <ul class="list-unstyled">
                <li>Veuillez renseigner 2 ou 4 réponses</li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
    <input type="hidden" id="add_an_other" name="add_an_other" value="0"/>
    <button type="button" id="btn_submit_form" class="btn btn-success">Sauvegarder</button>
    <button type="button" id="btn_submit_form_and_add" class="btn btn-success">Sauvegarder et Ajout</button>
    <a href="/examen/afficher?id=<?php echo $this->id_examen; ?>" class="btn btn-warning">Annuler</a>
</form>