<h2>Création d'une question</h2>

<form method="post" class="form-horizontal" action="/question/saveQuestion" enctype="multipart/form-data">
    <input type="hidden" name="id_examen" id="id_examen" value="<?php echo $this->id_examen; ?>"/>

    <!-- Numéro -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="numero_question">Numéro : </label>

        <div class="col-sm-10">
            <input class="form-control" name="numero_question" id="numero_question"
                   placeholder="Numéro de la question" type="number"/>
        </div>
    </div>
    <!-- Enonce -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="question_enonce">Enoncé de la question : </label>

        <div class="col-sm-10">
            <textarea class="form-control" name="question_enonce" id="question_enonce"
                      placeholder="Enoncé de la question"></textarea>
        </div>
    </div>
    <!-- Réponse A -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_A">Réponse A : </label>

        <div class="input-group col-sm-10">
            <span class="input-group-addon">
                <input name="is_correct_A" id="is_correct_A" type="checkbox"/>
            </span>
            <input class="form-control" name="enonce_A" id="enonce_A" placeholder="Réponse A"/>
        </div>
    </div>
    <!-- Réponse B -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_B">Réponse B : </label>

        <div class="input-group col-sm-10">
            <span class="input-group-addon">
                <input name="is_correct_B" id="is_correct_B" type="checkbox"/>
            </span>
            <input class="form-control" name="enonce_B" id="enonce_B" placeholder="Réponse B"/>
        </div>
    </div>
    <!-- Réponse C -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_C">Réponse C : </label>

        <div class="input-group col-sm-10">
            <span class="input-group-addon">
                <input name="is_correct_C" id="is_correct_C" type="checkbox"/>
            </span>
            <input class="form-control" name="enonce_C" id="enonce_C" placeholder="Réponse C"/>
        </div>
    </div>
    <!-- Réponse D -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="enonce_D">Réponse D : </label>

        <div class="input-group col-sm-10">
            <span class="input-group-addon">
                <input name="is_correct_D" id="is_correct_D" type="checkbox"/>
            </span>
            <input class="form-control" name="enonce_D" id="enonce_D" placeholder="Réponse D"/>
        </div>
    </div>
    <!-- Image -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="image">Image : </label>

        <div class="input-group col-sm-10">
            <input class="form-control" name="image" id="image" type="file"/>
        </div>
    </div>
    <button type="submit" class="btn btn-default">Valider</button>
</form>