<ol class="breadcrumb">
    <li><a href="/">Accueil</a></li>
    <li><a href="/user/lister">Gestion des utilisateurs</a></li>
    <li class="active">Création d'un nouvel utilisateur</li>
</ol>

<h2>Création d'un nouvel utilisateur</h2>

<form method="post" class="form-horizontal" action="/user/save" role="form" data-toggle="validator">

    <!-- Nom -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="name">Nom : </label>

        <div class="input-group col-sm-3">
            <input class="form-control" name="name" id="name" maxlength="30" type="text" autofocus required/>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <!-- Prénom -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="firstname">Prénom : </label>

        <div class="input-group col-sm-3">
            <input class="form-control" name="firstname" id="firstname" maxlength="30" type="text" required/>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <!-- UserName -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="username">Nom d'utilisateur : </label>

        <div class="input-group col-sm-3">
            <input class="form-control" name="username" id="username" maxlength="30" type="text" pattern="^([_A-z0-9]){3,}$"
                   data-remote="/user/validateUserName" data-remote-error="Nom d'utilisateur déjà utilisé" required/>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <!-- Password -->
    <div class="form-group">
        <label class="col-sm-2 control-label" for="password">Mot de passe : </label>

        <div class="input-group col-sm-3">
            <input class="form-control" name="password" data-minlength="6" id="password" maxlength="30" type="password" required/>
            <span class="help-block">Au moins 6 caractères</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="repeat-password">Retaper votre mot de passe : </label>

        <div class="input-group col-sm-3">
            <input class="form-control" name="repeat-password" id="repeat-password" maxlength="30"
                   data-match="#password" data-match-error="Les mots de passe ne sont pas identiques" type="password" required/>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Valider</button>
</form>